server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/userservice, classpath:config/authenticationservice, classpath:config/vulnerabilityservice, classpath:config/infrastructureservice, classpath:config/emailservice, classpath:config/commentservice