server:
  port : 8085

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8082/oauth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/